//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traicy.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traicy.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Achtung! ähnelt.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die chunked\chunked.png ähnelt.
        /// </summary>
        internal static string ChunkedImagePath {
            get {
                return ResourceManager.GetString("ChunkedImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ,  ähnelt.
        /// </summary>
        internal static string Comma {
            get {
                return ResourceManager.GetString("Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kamera Verbinden ähnelt.
        /// </summary>
        internal static string ConnectWebcam {
            get {
                return ResourceManager.GetString("ConnectWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbindung trennen ähnelt.
        /// </summary>
        internal static string DisconnectWebcam {
            get {
                return ResourceManager.GetString("DisconnectWebcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte trennen Sie zuerst die Verbindung zur Kamera, bevor Sie mit der Verarbeitung fortfahren! ähnelt.
        /// </summary>
        internal static string DisconnectWebcamFirst {
            get {
                return ResourceManager.GetString("DisconnectWebcamFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Executable files (*.exe)|*.exe|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string FileExtensionsInterpreter {
            get {
                return ResourceManager.GetString("FileExtensionsInterpreter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der gefundene Buchstabe ist  ähnelt.
        /// </summary>
        internal static string FoundLetter {
            get {
                return ResourceManager.GetString("FoundLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Buchstaben gefunden:  ähnelt.
        /// </summary>
        internal static string FoundLetters {
            get {
                return ResourceManager.GetString("FoundLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die gefundene Nummer ist  ähnelt.
        /// </summary>
        internal static string FoundNumber {
            get {
                return ResourceManager.GetString("FoundNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  Zahlen gefunden:  ähnelt.
        /// </summary>
        internal static string FoundNumbers {
            get {
                return ResourceManager.GetString("FoundNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich habe die folgenden  ähnelt.
        /// </summary>
        internal static string FoundTheFollowing {
            get {
                return ResourceManager.GetString("FoundTheFollowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die de-DE ähnelt.
        /// </summary>
        internal static string GermanVoice {
            get {
                return ResourceManager.GetString("GermanVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die JPEG (*.jpg;*.jpeg)|*.jpg;*.jpeg|PNG (*.png)|*.png|All files (*.*)|*.* ähnelt.
        /// </summary>
        internal static string ImageFilterOpenFileDialog {
            get {
                return ResourceManager.GetString("ImageFilterOpenFileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die images ähnelt.
        /// </summary>
        internal static string ImageFolderPath {
            get {
                return ResourceManager.GetString("ImageFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die jpg ähnelt.
        /// </summary>
        internal static string ImageTypeJPG {
            get {
                return ResourceManager.GetString("ImageTypeJPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die png ähnelt.
        /// </summary>
        internal static string ImageTypePNG {
            get {
                return ResourceManager.GetString("ImageTypePNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die configs ähnelt.
        /// </summary>
        internal static string JSONSettingsDirectoryName {
            get {
                return ResourceManager.GetString("JSONSettingsDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die configs\settings.json ähnelt.
        /// </summary>
        internal static string JSONSettingsFilePath {
            get {
                return ResourceManager.GetString("JSONSettingsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die log.txt ähnelt.
        /// </summary>
        internal static string Logfile {
            get {
                return ResourceManager.GetString("Logfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MNIST ähnelt.
        /// </summary>
        internal static string MNIST {
            get {
                return ResourceManager.GetString("MNIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die number ähnelt.
        /// </summary>
        internal static string ModelNumber {
            get {
                return ResourceManager.GetString("ModelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die pack://application:,,,/Traicy.GUI;component/resources/no-camera.png ähnelt.
        /// </summary>
        internal static string NoCameraUri {
            get {
                return ResourceManager.GetString("NoCameraUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es konnte keine Verbindung mit der Kamera hergestellt werden. Überprüfen Sie die Verbindung zum Gerät! ähnelt.
        /// </summary>
        internal static string NoConnectionMessage {
            get {
                return ResourceManager.GetString("NoConnectionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verbinden Sie die Kamera oder wählen Sie ein zu erkennendes Bild aus! ähnelt.
        /// </summary>
        internal static string NoObjectDetectionPossibleContent {
            get {
                return ResourceManager.GetString("NoObjectDetectionPossibleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Objekterkennung möglich! ähnelt.
        /// </summary>
        internal static string NoObjectDetectionPossibleHeader {
            get {
                return ResourceManager.GetString("NoObjectDetectionPossibleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ich konnte kein Objekt erkennen. ähnelt.
        /// </summary>
        internal static string NoResultFound {
            get {
                return ResourceManager.GetString("NoResultFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aus ähnelt.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An ähnelt.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prozent ähnelt.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  mit einer Wahrscheinlichkeit von  ähnelt.
        /// </summary>
        internal static string Probability {
            get {
                return ResourceManager.GetString("Probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Verarbeitung... ähnelt.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die python_resources\ ähnelt.
        /// </summary>
        internal static string PythonModelPath {
            get {
                return ResourceManager.GetString("PythonModelPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die python_resources\predict_number_with_ce.py ähnelt.
        /// </summary>
        internal static string PythonScriptPath {
            get {
                return ResourceManager.GetString("PythonScriptPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die C:\Users\Eva\Anaconda3\envs\customTFLearn\python.exe ähnelt.
        /// </summary>
        internal static string StandardPythonInterpreterPath {
            get {
                return ResourceManager.GetString("StandardPythonInterpreterPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Starte Objekterkennung ähnelt.
        /// </summary>
        internal static string StartObjectDetection {
            get {
                return ResourceManager.GetString("StartObjectDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mehr kann ich nicht erkennen. ähnelt.
        /// </summary>
        internal static string ThatIsAll {
            get {
                return ResourceManager.GetString("ThatIsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es ist ein Fehler aufgetreten! ähnelt.
        /// </summary>
        internal static string ThereHasBeenAnError {
            get {
                return ResourceManager.GetString("ThereHasBeenAnError", resourceCulture);
            }
        }
    }
}
